# theme based on https://github.com/pages-themes/minimal

title: React Rotterdam
theme: jekyll-theme-minimal
description: React Rotterdam is an independent meetup aimed at knowledge sharing, learning something new and meeting other people in the community.
google_analytics: UA-144563897-1
logo: /logos/MeetupLogo.png