# theme based on https://github.com/pages-themes/minimal

title: React Rotterdam
theme: jekyll-theme-minimal
description: Official web page of React Rotterdam meetup
google_analytics: UA-144563897-1
logo: /logos/MeetupLogo.png
