# theme based on https://github.com/pages-themes/minimal

title: React Rotterdam
theme: jekyll-theme-minimal
description: Official repository of React Rotterdam [Meetup](https://www.meetup.com/React-Rotterdam/)
google_analytics: UA-144563897-1
logo: /logos/MeetupLogo.png
